name: Sync Fork

on:
  schedule:
    - cron: '0 9 1/7 * *' # Runs at 09:00, every 7 days
  workflow_dispatch: # on button click

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: tgymnich/fork-sync@v1.8
        with:
          owner: ScoopInstaller
          base: master
          head: master
